config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    path: '',
    path_names:  { sign_up: :sign_up, sign_out: :logout, sign_in: :login },
    controllers: { registrations: :registrations, sessions: :sessions }

    root 'home#index'
    resources :bookings, only: [:index, :show, :new, :create, :update]
    resources :search,   only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :vehicle

  enum status: [:open, :closed]
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :validatable

  has_many :bookings
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  has_many :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
require_relative '../monads/bookings'

class BookingsController < ApplicationController
  before_action :authenticate_user!

  def index; end

  def show
    @booking = current_user.bookings.find(params[:id])
  end

  def new
    @vehicle = Vehicle.find(params[:vehicle_id])
  end

  def create
    result = ::Bookings::Create::Action.new.call(
      current_user, params: params
    )

    if result.success?
      @booking = result.value!
      redirect_to bookings_path
    else
      render :new
    end
  end

  def update
    @booking = current_user.bookings.find(params[:id].to_i)
    @booking.closed!

    redirect_back(fallback_location: root_path)
  end

  private

  def vehicle
    @vehicle ||= Vehicle.find(params[:vehicle_id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
end

app/controllers/search_controller.rb
require_relative '../monads/searchs'

class SearchController < ApplicationController
  def index
    result = ::Searchs::Index::Action.new.call(params: params)

    if result.success?
      @vehicles = result.value!
    else
      redirect_back(fallback_location: root_path)
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<%= form_tag bookings_path, method: :post do %>
  <input type="hidden" name="vehicle_id" value="<%= @vehicle.id%>">
  <input type="hidden" name="price" value="10">
  <input type="submit">
<% end %>

app/views/bookings/index.html.erb
<ul>
  <% current_user.bookings.each do |item|%>
    <li><a href="<%= booking_path(item) %>">Model: <%= item.vehicle.model%></a></li>
    <li>Price: <%= item.price%></li>
  <% end %>
</ul>

app/views/bookings/new.html.erb
<%= render 'form' %>

app/views/bookings/show.html.erb
<div>
  <p><%= @booking.vehicle.model %></p>
  <% if @booking.open? %>
    <%= form_tag booking_path(@booking), method: :put do %>
      <p><input type="submit" value="Close booking"></p>
    <% end %>
  <% else %>
    <p>Closed!</p>
  <% end %>
</div>

app/views/home/_form.html.erb
<form action="/search" method="get">
  <div class="form-group">
    <span class="form-label">Location</span>
    <input class="form-control" type="text" placeholder="City" name="city" required>
  </div>
  <div class="row">
    <div class="col-sm-6">
      <div class="form-group">
        <span class="form-label">Check In</span>
        <input class="form-control" name="start_date" type="date" required>
      </div>
    </div>
    <div class="col-sm-6">
      <div class="form-group">
        <span class="form-label">Check out</span>
        <input class="form-control" name="end_date" type="date" required>
      </div>
    </div>
  </div>
  <!-- <div class="row">
    <div class="col-sm-4">
      <div class="form-group">
        <span class="form-label">Rooms</span>
        <select class="form-control">
          <option>1</option>
          <option>2</option>
          <option>3</option>
        </select>
        <span class="select-arrow"></span>
      </div>
    </div>
    <div class="col-sm-4">
      <div class="form-group">
        <span class="form-label">Adults</span>
        <select class="form-control">
          <option>1</option>
          <option>2</option>
          <option>3</option>
        </select>
        <span class="select-arrow"></span>
      </div>
    </div>
    <div class="col-sm-4">
      <div class="form-group">
        <span class="form-label">Children</span>
        <select class="form-control">
          <option>0</option>
          <option>1</option>
          <option>2</option>
        </select>
        <span class="select-arrow"></span>
      </div>
    </div>
  </div> -->
  <div class="form-btn">
    <input type="submit" class="submit-btn" value="Search">
  </div>
</form>

app/views/home/index.html.erb
<div id="booking" class="section">
  <div class="section-center">
    <div class="container">
      <div class="row">
        <div class="col-md-7 col-md-push-5">
          <div class="booking-cta">
            <h1>Make your reservation</h1>
          </div>
        </div>
        <div class="col-md-4 col-md-pull-7">
          <div class="booking-form">
            <%= render 'form' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RentCar</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all' %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  </head>

  <body>
    <%= render 'shared/header' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/search/index.html.erb
<% @vehicles.each do |item| %>
  <div>
    <p><%= item.brand%></p>
    <p><%= item.model%></p>
    <p><a href="<%= new_booking_path(vehicle_id: item.id)%>" class="btn btn-primary">Go to bookings</a></p>
  </div>
<% end %>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light">
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link" href="<%= root_path %>">Home</a>
    </div>
  </div>
  <% if (!user_signed_in?) %>
    <%= link_to "Sign up", new_user_registration_path, class: 'navbar-brand' %>
    <%= link_to "Log in", new_user_session_path, class: 'navbar-brand' %>
  <% else %>
    <%= link_to "Log out", destroy_user_session_path, method: :delete, class: 'navbar-brand' %>
  <% end %>
</nav>

app/views/vehicles/show.html.erb
<div class="container">
  <div class="jumbotron">
    <div class="col-sm-8 mx-auto">
      <h1>Vehicle details</h1>
      <div class="row">
        <div class="col-md-4">
          <img src="https://images.unsplash.com/photo-1418489098061-ce87b5dc3aee?ixlib=rb-1.2.1&w=1000&q=80"
            class="card-img" alt="...">
            <p>asd sdf sdf sd</p>
        </div>
        <div class="col-md-8">
          <ul>
            <li><%= @vehicle.brand %> </li>
            <li><%= @vehicle.model %> </li>
            <li><%= @vehicle.plate_number %> </li>
            <li><%= @vehicle.seats_count %> </li>
            <li><%= @vehicle.large_bag_count %> </li>
            <li><%= @vehicle.small_bag_count %> </li>
            <li><%= @vehicle.doors_count %> </li>
            <li><%= @vehicle.air_conditioning %> </li>
            <li><%= @vehicle.automatic_gearbox %> </li>
            <li><%= @vehicle.free %> </li>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <div class="jumbotron">
    <div class="col-sm-8 mx-auto">
      <p>
        Supplier Location
        Sydney Airport
        50, Ross Smith Avenue, Control Tower at the end of Ross Smith Avenue, Mascot, Australia, NSW 2020
        Opening hours
        Mon - Sun 6am - 11pm
        Pick-up instructions
        Call 1800620408 (0061392222595) to arrange for collection. International Terminal 1: Exit the terminal, turn
        right following the signs to shuttle bus waiting area DOMESTIC TERMINAL 2 (Virgin, Jetstar and Regional
        Express) Exit the terminal, turn left following the signs to shuttle bus waiting area. DOMESTIC TERMINAL 3
        (Qantas) Exit the terminal, turn right following the signs to shuttle bus waiting area
      </p>
    </div>
    <a href="" class="btn">Go to book</a>
  </div>
</div>